services:
  - type: web
    name: telegram-cash-bot
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: 8467867383:AAGrCYHbRJqxZwPm2rS8YCjb5Wf_ulLVG_o
    port: 5000